### PR TITLE
[Fix] Fix the bug when using prefetch under multi-view methods, e.g., DenseCL

### PR DESCRIPTION
**Pull request by liming-ai**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

1. When training large dataset like ImageNet-21k, the memory leak issue usually exists.
2. When using prefetch loader, an error would occur due to [this line](https://github.com/open-mmlab/mmselfsup/blob/7d70d96602949cbac04f29ae91f661a3987b5de9/mmselfsup/datasets/utils.py#L181) ignore the multi-view situation

## Modification

1. Add a new DataSource to mitigate the memory leak following [mmcls](https://github.com/open-mmlab/mmclassification/pull/461)
2. Fix the bug when using prefetch under multi-view methods, e.g., DenseCL

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by liming-ai** [comment]
Can you please explain in more detail what is wrong with my PR submission? So that I can submit PR faster and better.

If you can, please explain in as much detail as possible, as I believe it would be useful for future contributors as well.

**Comment by cliangyu** [comment]
Refer to CONTRIBUTING.md
You missed out pre-commit forks for linting.

**Review by fangyixiao18 — COMMENTED** [review]
Sorry for later reply.
c-liangyu is right, you missed the pre-commit.

As for your PR, the modification of the ImageNet-21K dataset, we don't suggest merging it after the discussion because it is not solved. MMCls and us plan to solve it in the future versions. Or if you had a method to solve it totally, welcome to create PR.
So could you re-create one which only contains your second modification? We will review it!
Thanks for your contribution!

**Comment by liming-ai** [comment]
> Sorry for later reply. c-liangyu is right, you missed the pre-commit.
> 
> As for your PR, the modification of the ImageNet-21K dataset, we don't suggest merging it after the discussion because it is not solved. MMCls and us plan to solve it in the future versions. Or if you had a method to solve it totally, welcome to create PR. So could you re-create one which only contains your second modification? We will review it! Thanks for your contribution!

I will remake a PR to support the second modification. Actually, the memory leak question can be solved by using np.string in my experiments, which I have tried successfully, but only for the images. I have no idea how to combine this method for labels, I will propose a new PR to show that

**Comment by liming-ai** [comment]
> Sorry for later reply. c-liangyu is right, you missed the pre-commit.
> 
> As for your PR, the modification of the ImageNet-21K dataset, we don't suggest merging it after the discussion because it is not solved. MMCls and us plan to solve it in the future versions. Or if you had a method to solve it totally, welcome to create PR. So could you re-create one which only contains your second modification? We will review it! Thanks for your contribution!

Please check this PR, after that, I will create a new PR to show how to avoid the memory leak by limit implementation for now.

**Comment by fangyixiao18** [comment]
> Please check this PR, after that, I will create a new PR to show how to avoid the memory leak by limit implementation for now.

Could you run the pre-commit to fix the lint problem?

**Review by fangyixiao18 — APPROVED** [review]

**Review by Jiahao000 — APPROVED** [review]

**Review by YuanLiuuuuuu — APPROVED** [review]

**Pull request merged**
