### PR TITLE
[Fix] fix image channel bgr/rgb bug and update benchmarks

### PR DESCRIPTION
**Pull request by fangyixiao18**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

The default channel order of `mmcv.imfrombytes` is 'bgr', however, during training in some codebase, such as MMDet or MMSeg, they will convert the order to 'rgb' in normalization of dataset pipeline. To consist with them, we fix this bug.

## Modification

- [x] Add `channel_order` in class `BaseDataSource`, defaults to 'rgb'.
- [x] Update models

## BC-breaking (Optional)

**Note: Due to the channel order bug, we will update benchmark results as soon as possible.**

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by liming-ai** [comment]
Will this bug make the previously trained self-supervised model unusable? Or, do we need to retrain all the self-supervised models ?

**Comment by YuanLiuuuuuu** [comment]
> Will this bug make the previously trained self-supervised model unusable? Or, do we need to retrain all the self-supervised models ?
Please refer to this [issue](https://github.com/open-mmlab/mmselfsup/issues/212)

**Review by YuanLiuuuuuu — COMMENTED** [review]
I find some metrics are kept the same after fixing the rgb channel bug. It's really that case ?

**Comment by fangyixiao18** [comment]
> I find some metrics are kept the same after fixing the rgb channel bug. It's really that case ?

I update the results

**Review by YuanLiuuuuuu — APPROVED** [review]

**Review by Jiahao000 — APPROVED** [review]

**Pull request merged**
