### PR TITLE
Update model_zoo.md

### PR DESCRIPTION
**Pull request by Jason-Study**
Correct the link of CAE Readme.md

## Checklist

**Before PR**:

 [[CAE](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/simmim/README.md)](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/simmim/README.md)

**After PR**:

 [[CAE](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/cae/RAEDME.md)](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/cae/RAEDME.md)

### CODE REVIEW

**Comment by tonysy** [comment]
Hi, thanks for your contribution. Please run [pre-commit hook](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to resolve the lint issue and we will merge this PR.

**Review by tonysy — CHANGES_REQUESTED** [review]
Please use pre-commit hook to fix the lint issue. Thanks

**Comment by Jason-Study** [comment]
Excuse me, This is my first time to commit.  I have used the [pre-commit](https://pre-commit.com/) hook, and are there any problem?

**Comment by fangyixiao18** [comment]
> Excuse me, This is my first time to commit. I have used the [pre-commit](https://pre-commit.com/) hook, and are there any problem?

Thanks for your contribution, it is ok now

**Review by fangyixiao18 — APPROVED** [review]

**Comment by OpenMMLab-Assistant005** [comment]
Hi @Jason-Study ！First of all, we want to express our gratitude for your significant PR in the MMSelfSup project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
