### PR TITLE
Create r50_withoutsobel.py for deepclustering experiment

### PR DESCRIPTION
**Pull request by guochengqian**
This config file is for deepclustering without Sobel layer. 
I train it on 8 V100s and it gives Top-1 acc 50.398 and Top-5 acc 72.62 (ImageNet (last layer))

### CODE REVIEW

**Comment by XiaohangZhan** [comment]
Since the result is much lower than Deepcluster with sobel as expected, is it still necessary to include this config?

**Comment by XiaohangZhan** [comment]
You are welcome to implement deepcluster v2 which improves deepcluster by a large margin.

**Comment by guochengqian** [comment]
r50_withoutsobel.py gives 50.398, which is better than r50. (46.92) 
https://github.com/open-mmlab/OpenSelfSup/blob/master/docs/MODEL_ZOO.md#imagenet-linear-classification

but anyway, not important. Thank you!

**Comment by XiaohangZhan** [comment]
We may not only test on the last layer. Deepcluster performs better on the 4th layer (57.71). If deepcluster without sobel outperforms the nomal deepcluster on this layer, it is an important thing.

**Comment by guochengqian** [comment]
> We may not only test on the last layer. Deepcluster performs better on the 4th layer (57.71). If deepcluster without sobel outperforms the nomal deepcluster on this layer, it is an important thing.

Yeah. From the table in MODEL_ZOO.md, you show that the acc (last layer) of deepcluster with sobel is only 46.92. 
If it is the result you get, then my experiment shows that without sobel layer actually gives you better performance (but with suitable parameters, I train with lr 0.3 instead of 0.1 in your default setting). I use 0.1 for that it is the default lr in the official deepclustering code.

**Comment by XiaohangZhan** [comment]
> > We may not only test on the last layer. Deepcluster performs better on the 4th layer (57.71). If deepcluster without sobel outperforms the nomal deepcluster on this layer, it is an important thing.
> 
> Yeah. From the table in MODEL_ZOO.md, you show that the acc (last layer) of deepcluster with sobel is only 46.92.
> If it is the result you get, then my experiment shows that without sobel layer actually gives you better performance (but with suitable parameters, I train with lr 0.3 instead of 0.1 in your default setting). I use 0.1 for that it is the default lr in the official deepclustering code.

I mean, we should refer to the best result from ImageNet (Multi) and ImageNet (Last), rather than only focus on the last layer.  The original DeepCluster achieves 57.71 on feat4. Hence, I want to know the result on DeepCluster without sobel on feat4. If it outperforms 57.71, than it is an important discovery, I will surely include this config.

**Pull request merged**
