### PR TITLE
solve memory leak by limited implementation

### PR DESCRIPTION
**Pull request by liming-ai**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Solve the memory leak when loading ImageNet-21k, however, this implementation is limited since cannot load the labels. But the key to solve this issue is change `python.list` into `np.string`. For more details please refer to https://github.com/open-mmlab/mmselfsup/issues/217

This modify works for me on ImageNet-21k with many algorithms, which reduce the memory consume by a large margin and avoid the memory leak under standard 8-gpu machine.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by fangyixiao18** [comment]
Could you run the pre-commit to fix the lint problem? Thanks

**Comment by liming-ai** [comment]
> Could you run the pre-commit to fix the lint problem? Thanks

Sorry for that, I have no experience for the lint problem, so it takes some time. Besides, this limited implementation does not support to load labels, so it can only be used for selfsup, for mmcls, maybe you can expand it.

**Comment by fangyixiao18** [comment]
> Sorry for that, I have no experience for the lint problem, so it takes some time. Besides, this limited implementation does not support to load labels, so it can only be used for selfsup, for mmcls, maybe you can expand it.

Thank you for your contribution! We will review it later.

**Comment by fangyixiao18** [comment]
Could you checkout a new branch from dev0.7.0 and re-create a new PR? 
It is not supposed to create a PR from master branch.

**Comment by liming-ai** [comment]
> Could you checkout a new branch from dev0.7.0 and re-create a new PR? It is not supposed to create a PR from master branch.

OK, I will close this PR and re-create a new PR

**Pull request closed without merging**
