### PR TITLE
[Docs] Fix moco v2 and byol links by swapping them

### PR DESCRIPTION
**Pull request by bencwallace**
## Motivation

The links are swapped.

## Modification

Swapped the links.

### CODE REVIEW

**Comment by fangyixiao18** [comment]
Thanks for your contribution. could you also help us swap the links in https://github.com/open-mmlab/mmselfsup/blob/master/README_zh-CN.md

**Comment by bencwallace** [comment]
Done.

**Comment by YuanLiuuuuuu** [comment]
@fangyixiao18 consider creating a PR to fix the lint in the master branch?

**Comment by fangyixiao18** [comment]
> @fangyixiao18 consider creating a PR to fix the lint in the master branch?

https://github.com/open-mmlab/mmselfsup/pull/688

**Comment by fangyixiao18** [comment]
> Done.

Hi, could you please rebase on master branch? we fixed the isort error in lint check

**Review by fangyixiao18 — APPROVED** [review]

**Pull request merged**
