### PR TITLE
Add SimSiam Model

### PR DESCRIPTION
**Pull request by youqingxiaozhua**
Add SimSiam Model (http://arxiv.org/abs/2011.10566)

### CODE REVIEW

**Comment by XiaohangZhan** [comment]
Thank you so much! Besides, could you please update the tables in the MODEL_ZOO.md, including the model download links and the evaluation results (at least on SVM and ImageNet Linear classification), so that we can add your name there?

**Comment by youqingxiaozhua** [comment]
> Thank you so much! Besides, could you please update the tables in the MODEL_ZOO.md, including the model download links and the evaluation results (at least on SVM and ImageNet Linear classification), so that we can add your name there?

No problem. I will update you when it’s done.

**Comment by XiaohangZhan** [comment]
We are constructing a wechat group of openselfsup contributors, could you provide your wechat account to my email: xiaohangzhan@outlook.com?

**Comment by summelon** [comment]
May I ask why this pull request is still under merging?

**Comment by youqingxiaozhua** [comment]
> May I ask why this pull request is still under merging?

Sorry about that, but I still can not reproduce the accuracy reported by the original paper, there may be some mistakes in my code. Maybe in the late of this month, I will have a double-check.

**Comment by poodarchu** [comment]
You can refer to https://github.com/poodarchu/SelfSup to check your SimSiam implementation. @youqingxiaozhua @XiaohangZhan @summelon

**Pull request closed without merging**
